name: data-engineering
services:
  postgres:
    image: postgres:17.4
    container_name: postgres-data-engineering
    restart: unless-stopped
    networks:
      - data-net
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.3
    container_name: redis-data-engineering
    restart: unless-stopped
    networks:
      - data-net
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}" ] # Start Redis with mandatory password protection using custom config
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio-data-engineering
    restart: unless-stopped
    networks:
      - data-net
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data

  mc:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    container_name: minio-mc-data-engineering
    user: root
    depends_on:
      - minio
    networks:
      - data-net
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: > # One-time setup: wait for MinIO, create buckets and set public access policies to the raw bucket
      /bin/sh -c "
        until mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
          sleep 2;
        done &&
        mc mb --ignore-existing myminio/${MINIO_RAW_BUCKET} &&
        mc anonymous set public myminio/${MINIO_RAW_BUCKET}
      "

  grafana:
    image: grafana/grafana:12.4
    container_name: grafana-data-engineering
    restart: unless-stopped
    networks:
      - data-net
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_PLUGINS_PREINSTALL: yesoreyeram-infinity-datasource
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      # Persist Grafana data and provisioning configs and mount custom dashboards
      - ./grafana-data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./Grafana_Dashboards:/etc/grafana/dashboards

  prefect-server:
    image: prefecthq/prefect:3-python3.11
    container_name: prefect-server-data-engineering
    restart: unless-stopped
    networks:
      - data-net
    command: prefect server start --host 0.0.0.0
    environment:
      PREFECT_API_URL: http://127.0.0.1:4200/api
      PREFECT_UI_URL: http://127.0.0.1:4200
    ports:
      - "4200:4200"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      # Using Python socket to check port status as curl is missing in the base image
      test: [ "CMD-SHELL", "python -c 'import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.connect((\"127.0.0.1\", 4200))'" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: ../GrafanaApi
    container_name: assets-api-data-engineering
    restart: unless-stopped
    networks:
      - data-net
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  scheduler:
    build:
      context: ../GrafanaApi
    container_name: prefect-scheduler-data-engineering
    restart: unless-stopped
    networks:
      - data-net
    command: python -m app.scheduler.scheduler
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api # Connect to the central Prefect server for orchestration
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_RAW_BUCKET: ${MINIO_RAW_BUCKET}
      MINIO_DWH_BUCKET: ${MINIO_DWH_BUCKET}
      KAGGLE_API_TOKEN: ${KAGGLE_API_TOKEN}
    depends_on:
      # Wait for all infra components to be healthy before starting ETL scheduler to ensure smooth orchestration and avoid connection issues at startup
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      prefect-server:
        condition: service_healthy
      minio:
        condition: service_started

volumes:
  db:
    driver: local

networks:
  data-net:
    driver: bridge
