name: data-engineering
services:
  postgres:
    image: postgres:17.4
    container_name: postgres-data-engineering
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.4.3
    container_name: redis-data-engineering
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}" ]

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio-data-engineering
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data

  mc:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    container_name: minio-mc-data-engineering
    user: root
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        until mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
          sleep 2;
        done &&
        mc mb --ignore-existing myminio/raw &&
        mc mb --ignore-existing myminio/dwh &&
        mc anonymous set public myminio/raw &&
        mc anonymous set public myminio/dwh
      "

  grafana:
    image: grafana/grafana:12.4
    container_name: grafana-data-engineering
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_INSTALL_PLUGINS: yesoreyeram-infinity-datasource
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./Grafana_Dashboards:/etc/grafana/dashboards

  api:
    build:
      context: ../GrafanaApi
    container_name: assets-api-data-engineering
    restart: unless-stopped
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  scheduler:
    build:
      context: ../GrafanaApi
    container_name: prefect-scheduler-data-engineering
    restart: unless-stopped
    command: python -m app.etl.scheduler
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_RAW_BUCKET: ${MINIO_RAW_BUCKET}
      MINIO_DWH_BUCKET: ${MINIO_DWH_BUCKET}
      KAGGLE_API_TOKEN: ${KAGGLE_API_TOKEN}
    depends_on:
      - postgres
      - redis

volumes:
  db:
    driver: local
