apiVersion: 1
datasources:
  - name: Infinity API
    type: yesoreyeram-infinity-datasource
    uid: data-engineering-datasource
    access: proxy
    url: http://api:8000 
    isDefault: true
    jsonData:
      global_queries: []